### ISSUE TITLE
Set up AppSync credentials

### ISSUE THREAD

**Issue by metalc0der** [sony/appsync-client-go#12]
Hello.
I'm willing to use your package to make query requests to appsync. Is there a way to configure appsync credentials? Do you have any example of this?

**Comment by KazuhitoNakamura** [comment]
Hello, @metalc0der.

Thank you for your interest in appsync-client-go.

Here is a sample code to configure appsync credentials with iam authorization.
https://github.com/sony/appsync-client-go/blob/master/test/EventApp/appsync_eventapp.go#L42

I hope this answers your question.

**Comment by KazuhitoNakamura** [comment]
Let me close this issue, thank you.
