### ISSUE TITLE
How to authorize with API Key

### ISSUE THREAD

**Issue by Punith13** [sony/appsync-client-go#13]
Hi, 

I am using Appsync with API key authorization. Does this library allow for it?

**Comment by KazuhitoNakamura** [comment]
Hello, @Punith13.

Thank you for your interest in appsync-client-go and sorry for the late response.

Yes, we have `WithAPIKey` functions, please refer to the API document.

- https://pkg.go.dev/github.com/sony/appsync-client-go@v1.2.1/graphql#WithAPIKey (for Query and Mutation)
- https://pkg.go.dev/github.com/sony/appsync-client-go@v1.2.1#WithAPIKey (for Subscription)

**Comment by Punith13** [comment]
Thank you @KazuhitoNakamura
