### ISSUE TITLE
Using API key instead of AWS credentials

### ISSUE THREAD

**Issue by modusCell** [sony/appsync-client-go#14]
Hi guys, 
Is it possible to use API key, Cognito credentials or Lambda auth instead using credentials for all query, mutations, sub and pub?
Cheers,
-mo

**Comment by KazuhitoNakamura** [comment]
Hello, @modusCell.

Thank you for your interest in appsync-client-go.

As for API key, [WithAPIKey](https://pkg.go.dev/github.com/sony/appsync-client-go@v1.2.1/graphql#WithAPIKey) function could set X-Api-Key to http request header.
As for Cognito credentials or Lambda auth, you may use [WithCredential](https://pkg.go.dev/github.com/sony/appsync-client-go@v1.2.1/graphql#WithCredential) function may be usable  if your appsync server needs Authorization header.

I hope this answers your question.

**Comment by modusCell** [comment]
Hi @KazuhitoNakamura 
Thank you very much, I found it and it is working fine. 

Can we use Lambda auth for appsync.NewPureWebSocketSubscriber? 

Cheers,
-mo

**Comment by KazuhitoNakamura** [comment]
Hi, @modusCell.

Thank you for your confirmation, I am happy to hear that.

> Can we use Lambda auth for appsync.NewPureWebSocketSubscriber?

Unfortunately, we have no functions to do that for now.
But according to this [document](https://docs.aws.amazon.com/appsync/latest/devguide/real-time-websocket-client.html#header-parameter-format-based-on-appsync-api-authorization-mode), [WithOIDC](https://pkg.go.dev/github.com/sony/appsync-client-go#WithOIDC) function may be usable for that as workaround.
My understating is that same http header contents are needed for `Amazon Cognito user pools and OpenID Connect (OIDC)` and `Lambda authorization`.

BR,
Kazuhito.

**Comment by modusCell** [comment]
Hi @KazuhitoNakamura 
Thank you appsync.WithOIDC(host, authString) worked! 

I am using your example `appsync_eventapp.go`.  It is working fine for querying, mutations and subscriptions to an event. However when subscriptions event handler triggered 

```
msg, ok := <-ch
if !ok {
    log.Fatal("ch has been closed.")
}
_, _ = pp.Println(msg)
```

that leading to panic even after response printed to debug console. 

`&{<nil> map[onUpdateEvent:map[description:descriptionData name:updatedNameData when:whenData where:whereData]] <nil> <nil>}`

I am not sure what's causing the panic, any clue would be appreciated. 

Cheers,
-mo

**Comment by KazuhitoNakamura** [comment]
Hello, @modusCell 

I'm afraid that your code has some changes from `appsync_eventapp.go`
Could you please confirm if closing or sending values to a closed channel?

**Comment by modusCell** [comment]
hi @KazuhitoNakamura 

Here is my code directly copied from your example. There is no problem on subscription side. I can see that on CloudWatch logs.

```
{
    "logType": "RequestSummary",
    "requestId": "748f848c-0768-42cd-82b5-7367b8ec4cde",
    "graphQLAPIId": "APP_ID",
    "statusCode": 200,
    "latency": 22255000
}
```

When AppSync side publishes a message it is receiving and crashing while trying to parse JSON payload. 

```
func ExampleClient_graphqlws_subscription() {
	subscription := fmt.Sprintf(`subscription MySubscription {
		onUpdateEvent {
		  description
		  id
		  name
		  when
		  where
		}
	  }`)

	ch := make(chan *graphql.Response)
	subscriber := appsync.NewPureWebSocketSubscriber(
		strings.Replace("API_URL", "https", "wss", 1),
		graphql.PostRequest{
			Query: subscription,
		},
		func(r *graphql.Response) { ch <- r },
		func(err error) { log.Println(err) },
		appsync.WithOIDC("UPI_URL", "a"),
	)

	if err := subscriber.Start(); err != nil {
		log.Fatalln(err)
	}
	defer subscriber.Stop()

	response := <-ch
	fmt.Println(response)
	data := new(string)
	if err := response.DataAs(data); err != nil {
		log.Fatalln(err, response)
	}
	fmt.Println(*data)
}
```

Thank you.
Cheers,
-mo

**Comment by KazuhitoNakamura** [comment]
Hello, @modusCell 
I am so sorry to keep you waiting.

I think `data := new(string)` is a wrong type for `DataAs(data)`.
```golang
...
	data := new(string)
	if err := response.DataAs(data); err != nil {
		log.Fatalln(err, response)
	}
```

I suggest defining a struct for the payload.

```golang
...
	type event struct {
		ID          string  `json:"id"`
		Name        *string `json:"name"`
		Where       *string `json:"where"`
		When        *string `json:"when"`
		Description *string `json:"description"`
	}
	data := new(event)
	if err := response.DataAs(data); err != nil {
		log.Fatalln(err, response)
	}
```

BR,
Kazuhito.

**Comment by KazuhitoNakamura** [comment]
Sorry, but let me close this issue.
