### ISSUE TITLE
appsync.Client: Possibility to add a custom header to the requests

### ISSUE THREAD

**Issue by bubenkoff** [sony/appsync-client-go#21]
Currently implementation of appsync.Client doesn't allow setting a custom header for the requests.
This can be implemented by adding WithHTTPHeader option, for example.
The important use case can be for adding secret additional headers.

**Comment by KazuhitoNakamura** [comment]
Hello, @bubenkoff.

Thank you for your interest in appsync-client-go.

That's a good idea, so I will add WithHTTPHeader method to graphql.Option.
Please give me some time to add it.

**Comment by bubenkoff** [comment]
Thanks so much for your help!

**Comment by KazuhitoNakamura** [comment]
Hello, @bubenkoff.

I released the WithHTTPHeader as v1.4.0.
Can you please confirm that it is what you expected?

**Comment by bubenkoff** [comment]
thank you so much! It's exactly what was needed!
