### ISSUE TITLE
client_option - Allow using aws sdk v2 v4 signer

### ISSUE THREAD

**Issue by bubenkoff** [sony/appsync-client-go#23]
There's WithIAMAuthorization, and only the signer from AWS SDK v1 is supported.
Please add the support for SDK v2 v4 signer: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/aws/signer/v4#pkg-overview
Thanks!

**Comment by KazuhitoNakamura** [comment]
Hello, @bubenkoff.

Please give me some time to add it again.
Just to make sure, I'm thinking of migrating the sdk version to v2.
Does it meet your expectations?

**Comment by bubenkoff** [comment]
absolutely!
that's the best option - I agree. But it needs a major version change for
the package.
And for those who still use v1, they can pin to the old major version.

**Comment by KazuhitoNakamura** [comment]
Thank you for your suggestions.
Let me consider the possibility of coexistance the sdk v1 and v2.

**Comment by KazuhitoNakamura** [comment]
Hello, @bubenkoff.

I added two apis [WithIAMAuthorizationV2](https://pkg.go.dev/github.com/sony/appsync-client-go@v1.5.0#WithIAMAuthorizationV2) for query/mutation, and [WithIAMV2](https://pkg.go.dev/github.com/sony/appsync-client-go@v1.5.0#WithIAMV2) for subscription to v1.5.0 release.
Can you please confirm that it is what you expected?

Here is the sample code to use these apis.
https://github.com/sony/appsync-client-go/blob/master/test/EventApp/appsync_eventapp.go

**Comment by bubenkoff** [comment]
@KazuhitoNakamura thank you so much, it works like a charm!
