### ISSUE TITLE
adding slog for additional logging

### ISSUE THREAD

**Issue by jeremyforan** [sony/appsync-client-go#30]
Hello,

I am wondering if there is interest in adding an slog logger to the code base. https://go.dev/blog/slog

PROS: slog is a structured logging library that enhances logging capabilities in projects. It enables projects that import the module to configure log levels according to their needs. This feature allows for more precise control over what is logged, ensuring that developers can focus on the most relevant log information. 

CONS: The library was added to the standard library in 1.21. Go version 1.21 would be required to support this library.

If this is something you think would be beneficial I would be happy to start writing it.

Kind regards,

**Comment by KazuhitoNakamura** [comment]
Hello, @jeremyforan.

Thank you for your suggestions. 
I support the introduction of slog. I have experience using slog in another project, so I understand its benefits.

**Comment by jeremyforan** [comment]
Hello @KazuhitoNakamura,

I will make a pull request. Also, I have made a small change for you to consider.

`
func (r *realtimeWebSocketOperation) readLoop() {
...
_, payload, err := r.ws.ReadMessage()
if err != nil {
	if netErr, ok := err.(net.Error); ok && netErr.Timeout() {
		slog.Warn("connection timeout")
	} else {
		slog.ErrorContext(r.ctx, "error reading message", "error", err)
	}
	r.onConnectionLost(err)
	return
}
`
We were getting intermittent "connection reset by peer" message. It looked like AWS is closing the session without warning. This would happen after a day or two of continues connection. Because the error was not a timeout the onConnectionLost wasn't be called. 

The change will always result in r.onConnectionLost(err) on a r.ws.ReadMessage() error. 

What do you think? Is there other considerations to be made here?

**Comment by KazuhitoNakamura** [comment]
Thank you so much for your pull request, I have confirmed the pull request.

I don't think this change will result in the expected behavior since onConnectionLost is always called when a ReadMessage error occurs and is not limited to the error we want to resolve this time.

Is it possible to know the type of error that occurred this time?

**Comment by jeremyforan** [comment]
It is difficult to capture the error as it is intermittent. It can take 2-3 days to occur. Currently we have a ticket open with AWS and they have escalated this issue to the AppSync team.

I tried using the syscall.ECONNRESET error type, based on this article https://gosamples.dev/connection-reset-by-peer/ but it did not seem to capture the error in testing:

```go
if errors.Is(err, syscall.ECONNRESET) {
            log.Print("This is connection reset by peer error")
        }
```

Is there a efficient way to validate the connection is still valid? That way if there is an error we can check if the connection is still valid.

```go
		_, payload, err := r.ws.ReadMessage()
		if err != nil {
			if netErr, ok := err.(net.Error); ok && netErr.Timeout() {
				slog.Warn("connection timeout")
				r.onConnectionLost(err)
				return
			} else {
				// check if connection has been lost
				slog.ErrorContext(r.ctx, "error reading message", "error", err)
				r.onConnectionLost(err)
				return
			}
				slog.Warn("error reading message", "error", err)
			return
		}
```

**Comment by KazuhitoNakamura** [comment]
I apologize for the late reply.
I’m afraid, I'm not sure that way to check if connection has been lost for now.
I will read the source code to see if there are any errors that validate the connection has been broken.

To introduce slog ahead of time, could you remove this small change from the #31?

**Comment by jeremyforan** [comment]
Hey @KazuhitoNakamura 

I agree with you.

I will push the changes as per your comment so that we can include the slog functionality. I will push the changes shortly.

**Comment by KazuhitoNakamura** [comment]
I found it quite difficult to check if the connection was lost because there are several errors defined in errors.New().

* [ReadMessage()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L1091)
    *  [NextReader()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L998)
       * [advanceFrame()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L794)
           * [CopyN()](https://github.com/golang/go/blob/release-branch.go1.20/src/io/io.go#L361)
               * [Copy()](https://github.com/golang/go/blob/release-branch.go1.20/src/io/io.go#L385) 
                   * [copyBuffer()](https://github.com/golang/go/blob/release-branch.go1.20/src/io/io.go#L405)
                       * [Read()](https://github.com/golang/go/blob/release-branch.go1.20/src/io/io.go#L427)
                           * [Read()](https://github.com/golang/go/blob/release-branch.go1.20/src/bufio/bufio.go#L208)
                               * [Read()](https://github.com/golang/go/blob/release-branch.go1.20/src/net/net.go#L179)
                                   * [syscall.EINVAL](https://github.com/golang/go/blob/release-branch.go1.20/src/net/net.go#L181) 
                                   * [OpError or io.EOF](https://github.com/golang/go/blob/release-branch.go1.20/src/net/net.go#L185)
                       * [errInvalidWrite](https://github.com/golang/go/blob/release-branch.go1.20/src/io/io.go#L433)
                       * [ErrShortWrite](https://github.com/golang/go/blob/release-branch.go1.20/src/io/io.go#L442)
               * [EOF](https://github.com/golang/go/blob/release-branch.go1.20/src/io/io.go#L368)
                   * https://github.com/golang/go/blob/release-branch.go1.20/src/io/io.go#L44
           * [read()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L809)
               * [Peek()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L371)
                   * [Peek()](https://github.com/golang/go/blob/release-branch.go1.20/src/bufio/bufio.go#L135)
                       * [ErrNegativeCount](https://github.com/golang/go/blob/release-branch.go1.20/src/bufio/bufio.go#L137)
                       * [ErrBufferFull](https://github.com/golang/go/blob/release-branch.go1.20/src/bufio/bufio.go#L148)
                       * [io.ErrNoProgress](https://github.com/golang/go/blob/release-branch.go1.20/src/bufio/bufio.go#L119)
               * [errUnexpectedEOF](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L373) 
           * [handleProtocolError()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L866)
               * [handleProtocolError()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L866)
           * [setReadRemaining()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L888)
               * [setReadRemaining()](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L328)
                   * [ErrReadLimit](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L330) 
           * [handlePing](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L954)
               * [WriteControl](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L413) 
                   * [errBadWriteOpCode](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L415)
                   * [errInvalidControlFrame](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L418)
                   * [errWriteTimeout](https://github.com/gorilla/websocket/blob/v1.5.0/conn.go#L443)

...

**Comment by jeremyforan** [comment]
merge complete.
