### ISSUE TITLE
Silent Subscription Loss

### ISSUE THREAD

**Issue by jeremyforan** [sony/appsync-client-go#7]
Hey,

First, thanks for this library it has been a massive help.

I am looking to run a Linux service and receive notifications from an appsync service.  After a day or two, it looks like we are losing the subscription connection and it is silently failing.

Is this something that maybe cause by a timeout?  Do we need to do some sort of subscription 'keep-alive'?

Kind Regards

**Comment by KazuhitoNakamura** [comment]
Hi @jeremyforan 

Thank you for your interest in appsync-client-go.

Is onConnectionLost callback is set to [NewSubscriber](https://github.com/sony/appsync-client-go/blob/master/subscriber.go#L32)?
and this Silent Subscription Loss means the callback is not called if the connection lost?

**Comment by jeremyforan** [comment]
Thanks for the quick response.

I should have done a better job reviewing the code. This is what I have implemented and I wonder if I am taking the correct approach.

I am passing a chan to the callback function that publishes 'True' on when onConnectionLost event occurs.

when I receive that event in my select loop I overwrite my existing subscription with a new one.

```
case <-subscriptionLostChan:
    
    Log.Info("Subscription Lost, attempting to resubscribe")
    
   RadioUpdate, err = GraphAgent.SubscribeToRadioStateChanges(subscriptionLostChan)
    if err != nil {
	    Log.Fatalf("Unable to subscribe to event")
    }
    Log.Info("Resubscribed")
 



```

**Comment by KazuhitoNakamura** [comment]
Thank you for sharing us your code, I think this is a way my expected.
Could you please also share us your callback function code? 
If possible, I'd like to know capacity and length of the channel etc.

And did you have some logs(e.g Subscription Lost, attempting to resubscribe) if this issue occured?

**Comment by jeremyforan** [comment]
Here is the channel declaration

`subscriptionLostChan := make(chan bool)`

and then the function definition

```
func (g *GraphQLAgent) SubscribeToRadioStateChanges(subLost chan bool) (<-chan *Radio, error) {
	Log.Debug("Initiating Subscription")
	var err error

	subscription := subscribeString

	postRequest := graphql.PostRequest{
		Query: subscription,
	}
	subResponse, err := g.Client.Post(postRequest)

	if err != nil {
		Log.Errorf("Subscription Error: %s\n", err)
		return nil, err
	}

	ext, err := appsync.NewExtensions(subResponse)
	if err != nil {
		return nil, err
	}

	ch := make(chan *Radio, 4000)

	subscriber := appsync.NewSubscriber(*ext,
		func(r *graphql.Response) {
			AP := new(Radio)

			if err = r.DataAs(AP); err != nil {
				Log.Errorf("Unable to process Radio Subscription Update: %s\n", err)
			}
			ch <- AP
		},
		func(err error) {
			Log.Warnf("GraphQl Subscription has been lost: %e", err)
			subLost <- true
		},
	)

	if err = subscriber.Start(); err != nil {
		Log.Errorf("Unable to initiate Subscription: %s\n", err)
		return nil, err
	}
	return ch, nil
}
```

**Comment by KazuhitoNakamura** [comment]
Thank you for the information.
From my understanding,  `subscriber` variable scope is finished in SubscribeToRadioStateChanges function.
After that, I'm afraid that GC will drop `subscriber` and lose the connection silently.

**Comment by jeremyforan** [comment]
Hey Kaz,

This has resolved the problem.  I am able to re-establish the subscription in under a second.  Thank you so much for this library, it has been pivotal in developing our solution.

Logs:

```
time="2021-02-04T11:43:52-05:00" level=info msg="sending heartbeat"
time="2021-02-04T11:49:03-05:00" level=info msg="Session closure was detected: Process exited with status 1"
time="2021-02-04T11:49:03-05:00" level=info msg="Attempting reconnect"
time="2021-02-04T11:49:03-05:00" level=info msg=Authenticated

```

**Comment by jeremyforan** [comment]
Hey Kazuhito,

I have taken your advice and moved the subscriber struct into a parent struct that is in the main scope

```
type GraphQLAgent struct {
	Client *appsync.Client
	Subscription *appsync.Subscriber
}

func (g *GraphQLAgent) SubscribeToRadioStateChanges(subLost chan bool) (<-chan *Radio, error) {
	Log.Debug("Initiating Subscription")
	var err error

	subscriptionQuery := subscribeString

	postRequest := graphql.PostRequest{
		Query: subscriptionQuery,
	}
	subResponse, err := g.Client.Post(postRequest)

	if err != nil {
		Log.Errorf("Subscription Error: %s\n", err)
		return nil, err
	}

	ext, err := appsync.NewExtensions(subResponse)
	if err != nil {
		return nil, err
	}

	ch := make(chan *Radio, 4000)


	//TODO: Subscription may be dropped by
	g.Subscription = appsync.NewSubscriber(*ext,
		func(r *graphql.Response) {
			AP := new(Radio)

			if err = r.DataAs(AP); err != nil {
				Log.Errorf("Unable to process Radio Subscription Update: %s\n", err)
			}
			ch <- AP
		},
		func(err error) {
			Log.Warnf("GraphQl Subscription has been lost: %e", err)
			subLost <- true
		},
	)

	if err = g.Subscription.Start(); err != nil {
		Log.Errorf("Unable to initiate Subscription: %s\n", err)
		return nil, err
	}
	return ch, nil
}

```
