### ISSUE TITLE
Support for custom domains 

### ISSUE THREAD

**Issue by sirkuttin** [sony/appsync-client-go#9]
Right now the service being signed is hardcoded to "appsync". However for custom gql domains, these look like API Gateway, and the service for this needs to be "execute-api"

Regarding line 55 in client.go

**Comment by KazuhitoNakamura** [comment]
Hi @sirkuttin 

Thank you for your interest in appsync-client-go.
From my understanding, AWS AppSync does not support custom domains for now.
(https://github.com/aws/aws-appsync-community/issues/5)

Could you please tell me what custom gql domains mean?

**Comment by sirkuttin** [comment]
Sorry for the confusing initial post. As a work around for the custom domains, we have spun up an api gateway that translates the request to our appsync gql endpoint.

With this implementation, we need to sign the requests with service "execute-api", not "appsync". However, I understand that our solution is non-standard so I think the best option we have is to fork your repo.

**Comment by KazuhitoNakamura** [comment]
Thank you for the information, I understand your situation.
I think that's a good workaround for setting up a custom domain to appsync.
Please let me think too whether to support this custom domains.

**Comment by KazuhitoNakamura** [comment]
It seems that Appsync supports custom domain names, so let me close this issue.
https://aws.amazon.com/jp/blogs/mobile/introducing-custom-domain-names-for-aws-appsync-apis/
